// <auto-generated />
namespace Loupedeck.CodexDesktopPlugin;

public sealed class NewChatCommand : ShortcutCommandBase
{
    public NewChatCommand()
        : base("New chat", "Starts a new chat.", "Chat", VirtualKeyCode.KeyN, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class QuickChatCommand : ShortcutCommandBase
{
    public QuickChatCommand()
        : base("Quick chat", "Opens a quick chat.", "Chat", VirtualKeyCode.KeyN, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class ArchiveChatCommand : ShortcutCommandBase
{
    public ArchiveChatCommand()
        : base("Archive chat", "Archives the current chat.", "Chat", VirtualKeyCode.KeyA, ModifierKey.ControlOrCommand | ModifierKey.Shift)
    {
    }
}

public sealed class NewStandaloneChatCommand : ShortcutCommandBase
{
    public NewStandaloneChatCommand()
        : base("New standalone chat", "Opens a new standalone chat window.", "Chat", VirtualKeyCode.KeyO, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class OpenSideChatCommand : ShortcutCommandBase
{
    public OpenSideChatCommand()
        : base("Open side chat", "Opens the current chat in the side panel.", "Chat", VirtualKeyCode.KeyS, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class MarkAsUnreadCommand : ShortcutCommandBase
{
    public MarkAsUnreadCommand()
        : base("Mark as unread", "Marks the current chat as unread.", "Chat", VirtualKeyCode.KeyU, ModifierKey.ControlOrCommand | ModifierKey.Shift)
    {
    }
}

public sealed class TogglePinCommand : ShortcutCommandBase
{
    public TogglePinCommand()
        : base("Toggle pin", "Pins or unpins the current chat.", "Chat", VirtualKeyCode.KeyP, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class FindCommand : ShortcutCommandBase
{
    public FindCommand()
        : base("Find", "Finds text in the current view.", "Navigation", VirtualKeyCode.KeyF, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class BackCommand : ShortcutCommandBase
{
    public BackCommand()
        : base("Back", "Returns to the previous view.", "Navigation", VirtualKeyCode.Oem4, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class ForwardCommand : ShortcutCommandBase
{
    public ForwardCommand()
        : base("Forward", "Moves forward to the next view.", "Navigation", VirtualKeyCode.Oem6, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class NextRecentlyViewedChatCommand : ShortcutCommandBase
{
    public NextRecentlyViewedChatCommand()
        : base("Next recently viewed chat", "Moves to the next recently viewed chat.", "Navigation", VirtualKeyCode.Tab, ModifierKey.Control)
    {
    }
}

public sealed class NextTabCommand : ShortcutCommandBase
{
    public NextTabCommand()
        : base("Next tab", "Moves to the next open tab.", "Navigation", VirtualKeyCode.Oem6, ModifierKey.ControlOrCommand | ModifierKey.Shift)
    {
    }
}

public sealed class NextChatCommand : ShortcutCommandBase
{
    public NextChatCommand()
        : base("Next chat", "Moves to the next chat.", "Navigation", VirtualKeyCode.Oem6, ModifierKey.ControlOrCommand | ModifierKey.Shift)
    {
    }
}

public sealed class NextChatNeedingAttentionCommand : ShortcutCommandBase
{
    public NextChatNeedingAttentionCommand()
        : base("Next chat needing attention", "Moves to the next chat needing attention.", "Navigation", VirtualKeyCode.KeyA, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class PreviousRecentlyViewedChatCommand : ShortcutCommandBase
{
    public PreviousRecentlyViewedChatCommand()
        : base("Previous recently viewed chat", "Moves to the previous recently viewed chat.", "Navigation", VirtualKeyCode.Tab, ModifierKey.Control | ModifierKey.Shift)
    {
    }
}

public sealed class PreviousTabCommand : ShortcutCommandBase
{
    public PreviousTabCommand()
        : base("Previous tab", "Moves to the previous open tab.", "Navigation", VirtualKeyCode.Tab, ModifierKey.Control | ModifierKey.Shift)
    {
    }
}

public sealed class PreviousChatCommand : ShortcutCommandBase
{
    public PreviousChatCommand()
        : base("Previous chat", "Moves to the previous chat.", "Navigation", VirtualKeyCode.Oem4, ModifierKey.ControlOrCommand | ModifierKey.Shift)
    {
    }
}

public sealed class GoToRecentChat1Command : ShortcutCommandBase
{
    public GoToRecentChat1Command()
        : base("Go to recent chat 1", "Opens recent chat 1.", "Navigation", VirtualKeyCode.Key1, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class GoToRecentChat2Command : ShortcutCommandBase
{
    public GoToRecentChat2Command()
        : base("Go to recent chat 2", "Opens recent chat 2.", "Navigation", VirtualKeyCode.Key2, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class GoToRecentChat3Command : ShortcutCommandBase
{
    public GoToRecentChat3Command()
        : base("Go to recent chat 3", "Opens recent chat 3.", "Navigation", VirtualKeyCode.Key3, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class GoToRecentChat4Command : ShortcutCommandBase
{
    public GoToRecentChat4Command()
        : base("Go to recent chat 4", "Opens recent chat 4.", "Navigation", VirtualKeyCode.Key4, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class GoToRecentChat5Command : ShortcutCommandBase
{
    public GoToRecentChat5Command()
        : base("Go to recent chat 5", "Opens recent chat 5.", "Navigation", VirtualKeyCode.Key5, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class GoToRecentChat6Command : ShortcutCommandBase
{
    public GoToRecentChat6Command()
        : base("Go to recent chat 6", "Opens recent chat 6.", "Navigation", VirtualKeyCode.Key6, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class SwitchToChatCommand : ModeSwitchCommandBase
{
    public SwitchToChatCommand()
        : base("Switch to GPT", "Switches Codex Desktop to GPT.", "Navigation", MacDesktopMode.ChatGPT)
    {
    }
}

public sealed class SwitchToWorkCommand : ModeSwitchCommandBase
{
    public SwitchToWorkCommand()
        : base("Switch to Work", "Switches Codex Desktop to Work.", "Navigation", MacDesktopMode.Work)
    {
    }
}

public sealed class SwitchToCodexCommand : ModeSwitchCommandBase
{
    public SwitchToCodexCommand()
        : base("Switch to Codex", "Switches Codex Desktop to Codex.", "Navigation", MacDesktopMode.Codex)
    {
    }
}

public sealed class ToggleActivityViewCommand : ShortcutCommandBase
{
    public ToggleActivityViewCommand()
        : base("Toggle activity view", "Shows or hides the activity view.", "Navigation", VirtualKeyCode.KeyU, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class OpenBrowserTabCommand : ShortcutCommandBase
{
    public OpenBrowserTabCommand()
        : base("Open browser tab", "Opens a new browser tab.", "Panels", VirtualKeyCode.KeyT, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class OpenReviewTabCommand : MacDesktopCommandBase
{
    public OpenReviewTabCommand()
        : base("Open review tab", "Opens a review tab.", "Panels", MacDesktopCommand.OpenReviewTab)
    {
    }
}

public sealed class ReopenClosedTabCommand : ShortcutCommandBase
{
    public ReopenClosedTabCommand()
        : base("Reopen closed tab", "Reopens the most recently closed tab.", "Panels", VirtualKeyCode.KeyT, ModifierKey.ControlOrCommand | ModifierKey.Shift)
    {
    }
}

public sealed class ToggleBottomPanelCommand : ShortcutCommandBase
{
    public ToggleBottomPanelCommand()
        : base("Toggle bottom panel", "Shows or hides the bottom panel.", "Panels", VirtualKeyCode.KeyJ, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class ToggleBrowserPanelCommand : ShortcutCommandBase
{
    public ToggleBrowserPanelCommand()
        : base("Toggle browser panel", "Shows or hides the browser panel.", "Panels", VirtualKeyCode.KeyB, ModifierKey.ControlOrCommand | ModifierKey.Shift)
    {
    }
}

public sealed class ToggleSidebarCommand : ShortcutCommandBase
{
    public ToggleSidebarCommand()
        : base("Toggle sidebar", "Shows or hides the sidebar.", "Panels", VirtualKeyCode.KeyB, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class ToggleReviewPanelCommand : ShortcutCommandBase
{
    public ToggleReviewPanelCommand()
        : base("Toggle Review panel", "Shows or hides the Review panel.", "Panels", VirtualKeyCode.KeyB, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class OpenFolderCommand : ShortcutCommandBase
{
    public OpenFolderCommand()
        : base("Open folder", "Opens a project folder.", "Project", VirtualKeyCode.KeyO, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class ClearAllUnreadsCommand : ShortcutCommandBase
{
    public ClearAllUnreadsCommand()
        : base("Clear all unreads", "Clears every unread chat marker.", "App", VirtualKeyCode.Escape, ModifierKey.Shift)
    {
    }
}

public sealed class SettingsCommand : ShortcutCommandBase
{
    public SettingsCommand()
        : base("Settings", "Opens Codex Desktop settings.", "App", VirtualKeyCode.Comma, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class CloseTabCommand : ShortcutCommandBase
{
    public CloseTabCommand()
        : base("Close Tab", "Closes the current tab.", "General", VirtualKeyCode.KeyW, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class CloseCommand : ShortcutCommandBase
{
    public CloseCommand()
        : base("Close", "Closes the current view.", "General", VirtualKeyCode.F4, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class CopyDeeplinkCommand : ShortcutCommandBase
{
    public CopyDeeplinkCommand()
        : base("Copy deeplink", "Copies a link to the current chat.", "General", VirtualKeyCode.KeyL, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class CopyWorkingDirectoryCommand : ShortcutCommandBase
{
    public CopyWorkingDirectoryCommand()
        : base("Copy working directory", "Copies the current working directory.", "General", VirtualKeyCode.KeyC, ModifierKey.ControlOrCommand | ModifierKey.Shift)
    {
    }
}

public sealed class ForceReloadBrowserPageCommand : ShortcutCommandBase
{
    public ForceReloadBrowserPageCommand()
        : base("Force Reload Browser Page", "Reloads the browser page without cached content.", "General", VirtualKeyCode.KeyR, ModifierKey.ControlOrCommand | ModifierKey.Shift)
    {
    }
}

public sealed class OpenCommandMenuCommand : ShortcutCommandBase
{
    public OpenCommandMenuCommand()
        : base("Open command menu", "Opens the command menu.", "General", VirtualKeyCode.KeyK, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class ReloadBrowserPageCommand : ShortcutCommandBase
{
    public ReloadBrowserPageCommand()
        : base("Reload Browser Page", "Reloads the current browser page.", "General", VirtualKeyCode.KeyR, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class RenameChatCommand : ShortcutCommandBase
{
    public RenameChatCommand()
        : base("Rename chat", "Renames the current chat.", "General", VirtualKeyCode.KeyR, ModifierKey.ControlOrCommand | ModifierKey.AltOrOption)
    {
    }
}

public sealed class SearchFilesCommand : ShortcutCommandBase
{
    public SearchFilesCommand()
        : base("Search Files...", "Searches for files in the current project.", "General", VirtualKeyCode.KeyP, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class ShowKeyboardShortcutsCommand : ShortcutCommandBase
{
    public ShowKeyboardShortcutsCommand()
        : base("Show keyboard shortcuts", "Shows the Codex Desktop keyboard shortcuts.", "General", VirtualKeyCode.Oem2, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class GoToChat1Command : ShortcutCommandBase
{
    public GoToChat1Command()
        : base("Go to chat 1", "Opens chat 1.", "General", VirtualKeyCode.Key1, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class GoToChat2Command : ShortcutCommandBase
{
    public GoToChat2Command()
        : base("Go to chat 2", "Opens chat 2.", "General", VirtualKeyCode.Key2, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class GoToChat3Command : ShortcutCommandBase
{
    public GoToChat3Command()
        : base("Go to chat 3", "Opens chat 3.", "General", VirtualKeyCode.Key3, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class GoToChat4Command : ShortcutCommandBase
{
    public GoToChat4Command()
        : base("Go to chat 4", "Opens chat 4.", "General", VirtualKeyCode.Key4, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class GoToChat5Command : ShortcutCommandBase
{
    public GoToChat5Command()
        : base("Go to chat 5", "Opens chat 5.", "General", VirtualKeyCode.Key5, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class GoToChat6Command : ShortcutCommandBase
{
    public GoToChat6Command()
        : base("Go to chat 6", "Opens chat 6.", "General", VirtualKeyCode.Key6, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class GoToChat7Command : ShortcutCommandBase
{
    public GoToChat7Command()
        : base("Go to chat 7", "Opens chat 7.", "General", VirtualKeyCode.Key7, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class GoToChat8Command : ShortcutCommandBase
{
    public GoToChat8Command()
        : base("Go to chat 8", "Opens chat 8.", "General", VirtualKeyCode.Key8, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class GoToChat9Command : ShortcutCommandBase
{
    public GoToChat9Command()
        : base("Go to chat 9", "Opens chat 9.", "General", VirtualKeyCode.Key9, ModifierKey.ControlOrCommand)
    {
    }
}

public sealed class ToggleFileTreeCommand : ShortcutCommandBase
{
    public ToggleFileTreeCommand()
        : base("Toggle File Tree", "Shows or hides the project file tree.", "General", VirtualKeyCode.KeyE, ModifierKey.ControlOrCommand | ModifierKey.Shift)
    {
    }
}
