namespace Loupedeck.CodexDesktopPlugin;

public enum MacDesktopCommand
{
    OpenReviewTab,
    OpenTerminal,
    SwitchToChat,
    SwitchToWork,
    SwitchToCodex,
    OpenCommandMenu,
}

internal sealed record MacDesktopCommandSpec(
    String Name,
    IReadOnlySet<String> Labels,
    IReadOnlySet<String> CommandGroupLabels,
    IReadOnlySet<String> ShortcutHints,
    String? MenuCommandCharacter = null,
    Int64? MenuCommandModifiers = null,
    Int64? MenuVirtualKey = null,
    UInt16? FallbackKeyCode = null,
    UInt64 FallbackKeyFlags = 0);

internal static class MacDesktopCommandCatalog
{
    private static readonly IReadOnlySet<String> OpenReviewTabLabels =
        new HashSet<String>(StringComparer.OrdinalIgnoreCase)
        {
            "Abrir aba de revisão",
            "Abrir pestaña de revisión",
            "Abrir separador de revisão",
            "Apri la scheda Revisione",
            "Atidaryti peržiūros skirtuką",
            "Atvērt pārskatīšanas cilni",
            "Ava ülevaatuse vahekaart",
            "Avaa tarkistusvälilehti",
            "Buka tab peninjauan",
            "Buka tab semakan",
            "Buksan ang tab ng pagsusuri",
            "Deschide fila de revizuire",
            "Fungua kichupo cha ukaguzi",
            "Fur taabka dib-u-eegista",
            "Hap skedën e rishikimit",
            "İnceleme sekmesini aç",
            "Mở tab rà soát",
            "Obre la pestanya de revisió",
            "Odpri zavihek za pregled",
            "Open het tabblad controleren",
            "Open review tab",
            "Opna yfirferðarflipann",
            "Otevřít kartu Kontrola",
            "Otvori karticu Pregled",
            "Otvori karticu za pregled",
            "Otvoriť kartu s revíziou",
            "Otwórz kartę Recenzja",
            "Ouvrir l’onglet de révision",
            "Ouvrir l’onglet Révision",
            "Review-Tab öffnen",
            "Véleményezési lap megnyitása",
            "«Тексеру» қойындысын ашу",
            "Åbn fanen Gennemse",
            "Åpne fanen Gjennomgang",
            "Öppna granskningsfliken",
            "Άνοιγμα καρτέλας αναθεώρησης",
            "Відкрити вкладку рецензування",
            "Отвори го јазичето Преглед",
            "Отвори картицу за преглед",
            "Отвори раздела за преглед",
            "Открыть вкладку проверки",
            "Хянах табыг нээх",
            "Բացել «Վերանայում» ներդիրը",
            "افتح علامة تبويب المراجعة",
            "باز کردن زبانه بازبینی",
            "جائزہ ٹیب کھولیں",
            "पुनरावलोकन टॅब उघडा",
            "समीक्षा टैब खोलें",
            "রিভিউ ট্যাব খুলুন",
            "ਸਮੀਖਿਆ ਟੈਬ ਖੋਲ੍ਹੋ",
            "સમીક્ષા ટેબ ખોલો",
            "மதிப்பாய்வு தாவலைத் திற",
            "సమీక్ష ట్యాబ్‌ను తెరవండి",
            "ಪರಿಶೀಲನೆ ಟ್ಯಾಬ್ ತೆರೆಯಿರಿ",
            "അവലോകന ടാബ് തുറക്കുക",
            "เปิดแท็บตรวจสอบ",
            "ပြန်လည်သုံးသပ်မှု တဘ်ကို ဖွင့်ပါ",
            "მიმოხილვის ჩანართის გახსნა",
            "የግምገማ ትርን ክፈት",
            "レビュータブを開く",
            "打开审查选项卡",
            "開啟審核分頁",
            "開啟審閱分頁",
            "검토 탭 열기",
        };

    private static readonly IReadOnlySet<String> OpenTerminalLabels =
        new HashSet<String>(StringComparer.OrdinalIgnoreCase)
        {
            "Abrir Terminal",
            "Abrir terminal",
            "Apri terminale",
            "Atidaryti terminalą",
            "Atvērt termināli",
            "Ava terminal",
            "Avaa pääte",
            "Buka Terminal",
            "Buka terminal",
            "Buksan ang Terminal",
            "Buksan ang terminal",
            "Deschide terminalul",
            "Fungua Temino",
            "Fungua temino",
            "Fur Terminalka",
            "Fur terminalka",
            "Hap Terminalin",
            "Hap terminalin",
            "Mở terminal",
            "Obre el Terminal",
            "Obre el terminal",
            "Odpri Terminal",
            "Odpri terminal",
            "Open terminal",
            "Opna flugstöð",
            "Opna Terminal",
            "Otevřít terminál",
            "Otvori terminal",
            "Otvoriť terminál",
            "Otwórz terminal",
            "Ouvrir le terminal",
            "Terminal openen",
            "Terminal öffnen",
            "Terminali Aç",
            "Terminali aç",
            "Terminál megnyitása",
            "Åbn Terminal",
            "Åbn terminal",
            "Åpne terminal",
            "Öppna terminal",
            "Öppna terminalen",
            "Άνοιγμα τερματικού",
            "Відкрити термінал",
            "Отваряне на терминал",
            "Отваряне на терминала",
            "Отвори го терминалот",
            "Отвори терминал",
            "Открыть терминал",
            "Терминал нээх",
            "Терминалды ашу",
            "Բացել տերմինալը",
            "باز کردن پایانه",
            "فتح الطرفية",
            "فتح الوحدة الطرفية",
            "ٹرمینل کھولیں",
            "टर्मिनल उघडा",
            "टर्मिनल खोलें",
            "টার্মিনাল খুলুন",
            "ਟਰਮੀਨਲ ਖੋਲ੍ਹੋ",
            "ટર્મિનલ ખોલો",
            "டெர்மினலைத் திறந்திடுக",
            "முனையத்தைத் திற",
            "టెర్మినల్‌ను తెరవండి",
            "ಟರ್ಮಿನಲ್ ತೆರೆಯಿರಿ",
            "ടെർമിനൽ തുറക്കുക",
            "เปิดเทอร์มินัล",
            "စက်ဖွင့်ရန်",
            "တာမီနယ်ကို ဖွင့်ရန်",
            "ტერმინალის გახსნა",
            "ተርሚናልን ክፈት",
            "ターミナルを開く",
            "打开终端",
            "開啟終端機",
            "터미널 열기",
        };

    private static readonly IReadOnlySet<String> SwitchToChatLabels =
        new HashSet<String>(StringComparer.OrdinalIgnoreCase)
        {
            "Alternar para Chat",
            "Badili hadi Chat",
            "Beralih ke Chat",
            "Bytt til Chat",
            "Cambiar a Chat",
            "Canvia a Chat",
            "Chat に切り替え",
            "Chat으로 전환",
            "Chuyển sang Trò chuyện",
            "Comută la Chat",
            "Kalo te Bisedë",
            "Lumipat sa Chat",
            "Lülitu režiimile Chat",
            "Mudar para o Chat",
            "Overschakelen naar Chat",
            "Passa a Chat",
            "Passer au Clavardage",
            "Passer à Chat",
            "Perjungti į „Chat“",
            "Prebacivanje na Chat",
            "Preklopi na klepet",
            "Prepnúť na Chat",
            "Prijeđi na Chat",
            "Przełącz na Chat",
            "Pārslēgties uz Chat",
            "Přepnout na Chat",
            "Skift til Chat",
            "Skipta yfir í Chat",
            "Sohbet moduna geç",
            "Switch to Chat",
            "U wareeg Chat",
            "Vaihda Chat-tilaan",
            "Váltás Chat módra",
            "Växla till Chat",
            "Zu Chat wechseln",
            "Μετάβαση στο Chat",
            "Переключиться в режим «Чат»",
            "Перемкнутися на чат",
            "Превключване към Chat",
            "Премини на Разговор",
            "Пређи на Ћаскање",
            "Чат режиміне ауысу",
            "Чат руу шилжих",
            "Անցնել Զրույց",
            "الانتقال إلى وضع الدردشة",
            "تغییر به چت",
            "چیٹ پر سوئچ کریں",
            "चॅटवर स्विच करा",
            "चैट पर स्विच करें",
            "চ্যাটে যান",
            "ਚੈਟ 'ਤੇ ਸਵਿੱਚ ਕਰੋ",
            "ચૅટ પર સ્વિચ કરો",
            "அரட்டைக்கு மாற்று",
            "చాట్‌కు మారండి",
            "ಚಾಟ್‌ಗೆ ಬದಲಿಸಿ",
            "ചാറ്റിലേക്ക് മാറുക",
            "สลับเป็น Chat",
            "စကားပြောသို့ ပြောင်းရန်",
            "ჩატზე გადართვა",
            "ወደ ውይይት ቀይር",
            "切换到聊天",
            "切換至對話",
        };

    private static readonly IReadOnlySet<String> SwitchToWorkLabels =
        new HashSet<String>(StringComparer.OrdinalIgnoreCase)
        {
            "Badili hadi Work",
            "Beralih ke Work",
            "Bytt til Work",
            "Cambiar a Work",
            "Canvia a Work",
            "Chuyển sang Công việc",
            "Comută la Work",
            "Kalo te Punë",
            "Lumipat sa Work",
            "Lülitu režiimile Work",
            "Mudar para Work",
            "Overschakelen naar Work",
            "Passa a Work",
            "Passer à Work",
            "Perjungti į „Work“",
            "Prebacivanje na Work",
            "Preklopi na delo",
            "Prepnúť na Work",
            "Prijeđi na Work",
            "Przełącz na Work",
            "Pārslēgties uz Work",
            "Přepnout na Work",
            "Skift til Work",
            "Skipta yfir í Work",
            "Switch to Work",
            "U wareeg Work",
            "Vaihda Work-tilaan",
            "Váltás Work módra",
            "Växla till Work",
            "Work ಗೆ ಬದಲಿಸಿ",
            "Work に切り替え",
            "Work-க்கு மாற்று",
            "Work로 전환",
            "Zu Work wechseln",
            "Çalışma moduna geç",
            "Μετάβαση στο Work",
            "Ажил руу шилжих",
            "Жұмыс режиміне ауысу",
            "Переключиться в режим «Работа»",
            "Перемкнутися на Роботу",
            "Превключване към Work",
            "Премини на Работа",
            "Пређи на Посао",
            "Անցնել Աշխատանք",
            "الانتقال إلى وضع العمل",
            "تغییر به کار",
            "ورک پر سوئچ کریں",
            "कामावर स्विच करा",
            "वर्क पर स्विच करें",
            "কাজে স্যুইচ করুন",
            "ਵਰਕ 'ਤੇ ਸਵਿੱਚ ਕਰੋ",
            "કામ પર સ્વિચ કરો",
            "వర్క్‌కు మారండి",
            "ജോലിയിലേക്ക് മാറുക",
            "สลับไปใช้ Work",
            "အလုပ်သို့ ပြောင်းရန်",
            "მუშაობაზე გადართვა",
            "ወደ ሥራ ቀይር",
            "切换到工作",
            "切換至「工作」",
            "切換至工作",
        };

    private static readonly IReadOnlySet<String> SwitchToCodexLabels =
        new HashSet<String>(StringComparer.OrdinalIgnoreCase)
        {
            "Badili hadi Codex",
            "Beralih ke Codex",
            "Bytt til Codex",
            "Cambiar a Codex",
            "Canvia a Codex",
            "Chuyển sang Codex",
            "Codex 'ਤੇ ਸਵਿੱਚ ਕਰੋ",
            "Codex'e geç",
            "Codex руу шилжих",
            "Codex پر سوئچ کریں",
            "Codex पर स्विच करें",
            "Codex वर स्विच करा",
            "Codex પર સ્વિચ કરો",
            "Codex ಗೆ ಬದಲಿಸಿ",
            "Codex သို့ ပြောင်းရန်",
            "Codex に切り替え",
            "Codex-ке ауысу",
            "Codex-க்கு மாற்று",
            "Codex-ലേക്ക് മാറുക",
            "Codex-ზე გადართვა",
            "Codexకి మారండి",
            "Codex로 전환",
            "Comută la Codex",
            "Kalo te Codex",
            "Lumipat sa Codex",
            "Lülitu režiimile Codex",
            "Mudar para Codex",
            "Mudar para o Codex",
            "Overschakelen naar Codex",
            "Passa a Codex",
            "Passer à Codex",
            "Perjungti į „Codex“",
            "Prebacivanje na Codex",
            "Preklopi na Codex",
            "Prepnúť na Codex",
            "Prijeđi na Codex",
            "Przełącz na Codex",
            "Pārslēgties uz Codex",
            "Přepnout na Codex",
            "Skift til Codex",
            "Skipta yfir í Codex",
            "Switch to Codex",
            "Tukar ke Codex",
            "U wareeg Codex",
            "Vaihda Codexiin",
            "Váltás a Codexre",
            "Växla till Codex",
            "Zu Codex wechseln",
            "Μετάβαση στο Codex",
            "Переключиться на Codex",
            "Перемкнутися на Codex",
            "Превключване към Codex",
            "Премини на Codex",
            "Пређи на Codex",
            "Անցնել Codex",
            "الانتقال إلى Codex",
            "تغییر به Codex",
            "কোডেক্সে স্যুইচ করুন",
            "สลับไปใช้ Codex",
            "ወደ Codex ቀይር",
            "切换到 Codex",
            "切換至 Codex",
        };

    private static readonly IReadOnlySet<String> OpenCommandMenuLabels =
        new HashSet<String>(StringComparer.OrdinalIgnoreCase)
        {
            "Abrir menu de comandos",
            "Abrir menú de comandos",
            "Apri menu dei comandi",
            "Atidaryti komandų meniu",
            "Atvērt komandu izvēlni",
            "Ava käskluse menüü",
            "Avaa komentovalikko",
            "Befehlsmenü öffnen",
            "Buka menu arahan",
            "Buka menu perintah",
            "Buksan ang menu ng command",
            "Deschide meniul de comenzi",
            "Fungua menyu ya Command",
            "Fur liiska amarrada",
            "Hap menynë e komandave",
            "Komut menüsünü aç",
            "Mở menu lệnh",
            "Obre el menú d’ordres",
            "Odpri meni ukazov",
            "Opdrachtmenu openen",
            "Open command menu",
            "Opna skipanavalmynd",
            "Otevřít nabídku příkazů",
            "Otvori izbornik naredbi",
            "Otvori meni naredbi",
            "Otvoriť ponuku príkazov",
            "Otwórz menu poleceń",
            "Ouvrir le menu des commandes",
            "Parancsmenü megnyitása",
            "Åbn kommandomenu",
            "Åpne kommandomeny",
            "Öppna kommandomenyn",
            "Άνοιγμα μενού εντολών",
            "Відкрити меню команд",
            "Команда мәзірін ашу",
            "Командын цэсийг нээх",
            "Отваряне на менюто с команди",
            "Отвори мени команди",
            "Отвори мени со команди",
            "Открыть меню команд",
            "Բացել հրամանների ընտրացանկ",
            "باز کردن منوی دستور",
            "فتح قائمة الأوامر",
            "کمانڈ مینو کھولیں",
            "कमांड मेनू उघडा",
            "कमांड मेन्यू खोलें",
            "কমান্ড মেনু খুলুন",
            "ਕਮਾਂਡ ਮੀਨੂ ਖੋਲ੍ਹੋ",
            "કમાન્ડ મેનૂ ખોલો",
            "கட்டளை மெனுவைத் திறந்திடுக",
            "కమాండ్ మెనూను తెరవండి",
            "ಕಮಾಂಡ್ ಮೆನು ತೆರೆಯಿರಿ",
            "കമാൻഡ് മെനു തുറക്കുക",
            "เปิดเมนูคำสั่ง",
            "အမိန့်မီနူးကို ဖွင့်ပါ",
            "ბრძანებების მენიუს გახსნა",
            "የትዕዛዝ ምናሌን ክፈት",
            "コマンドメニューを開く",
            "打开命令菜单",
            "開啟指令選單",
            "명령 메뉴 열기",
        };

    public static MacDesktopCommandSpec Get(MacDesktopCommand command)
        => command switch
        {
            MacDesktopCommand.OpenReviewTab => new MacDesktopCommandSpec("Open review tab", OpenReviewTabLabels, MacDesktopCommandLocalization.PanelsGroupLabels, new HashSet<String>(StringComparer.OrdinalIgnoreCase) { "ControlShiftG", "CtrlShiftG", "⌃⇧G" }, FallbackKeyCode: 5, FallbackKeyFlags: MacAccessibilityNative.CgEventFlagControl | MacAccessibilityNative.CgEventFlagShift),
            MacDesktopCommand.OpenTerminal => new MacDesktopCommandSpec("Open terminal", OpenTerminalLabels, MacDesktopCommandLocalization.PanelsGroupLabels, new HashSet<String>(StringComparer.OrdinalIgnoreCase) { "Control`", "Ctrl`", "⌃`" }, MenuCommandCharacter: "`", MenuCommandModifiers: 12, MenuVirtualKey: 50),
            MacDesktopCommand.SwitchToChat => new MacDesktopCommandSpec("Switch to Chat", SwitchToChatLabels, MacDesktopCommandLocalization.NavigationGroupLabels, new HashSet<String>(StringComparer.OrdinalIgnoreCase)),
            MacDesktopCommand.SwitchToWork => new MacDesktopCommandSpec("Switch to Work", SwitchToWorkLabels, MacDesktopCommandLocalization.NavigationGroupLabels, new HashSet<String>(StringComparer.OrdinalIgnoreCase)),
            MacDesktopCommand.SwitchToCodex => new MacDesktopCommandSpec("Switch to Codex", SwitchToCodexLabels, MacDesktopCommandLocalization.NavigationGroupLabels, new HashSet<String>(StringComparer.OrdinalIgnoreCase)),
            MacDesktopCommand.OpenCommandMenu => new MacDesktopCommandSpec("Open command menu", OpenCommandMenuLabels, MacDesktopCommandLocalization.EmptyLabels, new HashSet<String>(StringComparer.OrdinalIgnoreCase) { "CommandK", "CmdK", "⌘K" }, MenuCommandCharacter: "K", MenuCommandModifiers: 0, MenuVirtualKey: 40, FallbackKeyCode: 40, FallbackKeyFlags: MacAccessibilityNative.CgEventFlagCommand),
            _ => throw new ArgumentOutOfRangeException(nameof(command), command, null),
        };
}
